CUSTOM_MATRIX=lite

DYNAMIC_TAPPING_TERM_ENABLE = yes
PROGRAMMABLE_BUTTON_ENABLE = yes

OS_DETECTION_ENABLE = yes
OS_DETECTION_DEBUG_ENABLE = yes

KEYBOARD_SHARED_EP = yes

FLASH_DRIVER = spi

QUANTUM_LIB_SRC += spi_master.c

SRC += matrix.c
